---
name: tox

on:
  push:
    branches:
      - "main"
      - "cp_fix_mytest"
  pull_request:
    branches:
      - "main"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tox:
    uses: abhikdps/team-devtools/.github/workflows/tox.yml@main
    with:
      max_python: "3.13"
      jobs_producing_coverage: 8

  tox-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tox-ansible, includes tox
        run: python3 -m pip install .

      - name: Generate matrix
        id: generate-matrix
        working-directory: tests/fixtures/unit/test_type
        run: |
          python3 -m tox --ansible --gh-matrix --conf tox-ansible.ini

    outputs:
      envlist: ${{ steps.generate-matrix.outputs.envlist }}

  test:
    needs: tox-matrix
    strategy:
      fail-fast: false
      matrix:
        entry: ${{ fromJson(needs.tox-matrix.outputs.envlist) }}
    name: ${{ matrix.entry.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install tox-ansible, includes tox
        run: python3 -m pip install .

      - name: Set up Python for testing
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.entry.python }}

      - name: Create example directory
        run: mkdir example

      - name: Run Collection creation script
        working-directory: tools
        run: ./create_collection.sh example.broken

      - name: Run tox test
        working-directory: tools/example
        run: python3 -m tox --ansible -e ${{ matrix.entry.name }} --conf tox-ansible.ini
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_passed:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.test.result }}',
          ]) == {'success'}"
