---
name: tox

on:
  push:
    branches:
      - "main"
      - "cp_fix_mytest"
  pull_request:
    branches:
      - "main"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tox:
    uses: abhikdps/team-devtools/.github/workflows/tox.yml@main
    with:
      max_python: "3.13"
      jobs_producing_coverage: 8

  integration:
    # needs: tox
    strategy:
      fail-fast: false
    name: integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Make test script executable
        working-directory: tools
        run: chmod +x test_all.sh

      - name: Run tox test
        working-directory: tools
        run: ./test_all.sh foo.bar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_passed:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.integration.result }}',
          ]) == {'success'}"
